### ISSUE TITLE
Error Report: Cannot read property 'value' of undefined

### ISSUE THREAD

**Issue by markrosenbaum** [urbit/bridge#1001]
## Context

This error occurred wile logging into bridge. 

I was logging in with the Ethereum address 0x5A30e92350C61960Dbb8c7D6E9F9e1f6C487280B

## Error

```
TypeError: Cannot read property 'value' of undefined
    at https://bridge.urbit.org/static/js/main.280ba267.chunk.js:1:237615
    at rs (https://bridge.urbit.org/static/js/2.e1a6ea4a.chunk.js:2:3293274)
    at qs (https://bridge.urbit.org/static/js/2.e1a6ea4a.chunk.js:2:3302841)
    at Qo (https://bridge.urbit.org/static/js/2.e1a6ea4a.chunk.js:2:3346723)
    at xl (https://bridge.urbit.org/static/js/2.e1a6ea4a.chunk.js:2:3332906)
    at Sl (https://bridge.urbit.org/static/js/2.e1a6ea4a.chunk.js:2:3332834)
    at Il (https://bridge.urbit.org/static/js/2.e1a6ea4a.chunk.js:2:3332697)
    at hl (https://bridge.urbit.org/static/js/2.e1a6ea4a.chunk.js:2:3329663)
    at https://bridge.urbit.org/static/js/2.e1a6ea4a.chunk.js:2:3279042
    at t.unstable_runWithPriority (https://bridge.urbit.org/static/js/2.e1a6ea4a.chunk.js:2:3356461)
```

In Bridge version 3.0.0.

**Comment by tomholford** [comment]
@markrosenbaum Thanks for the report. Which browser and login method are you using?

**Comment by markrosenbaum** [comment]
I am using chrome and I was logging in with recovery phrase.

**Comment by tomholford** [comment]
@markrosenbaum Yesterday we pushed an update with a performance improvement for the Recovery Phrase login flow (#995). Can you try again and report back if this resolves the issue?

**Comment by markrosenbaum** [comment]
Yep, Il go test it out right now.

**Comment by markrosenbaum** [comment]
Worked flawlessly.
![Screenshot 2022-03-24 at 4 06 31 PM](https://user-images.githubusercontent.com/57112559/160001141-aa169d6b-cb0d-45e6-b6b5-2fde02ac3258.png)

**Comment by tomholford** [comment]
Wonderful, thanks for the prompt turnaround!
