### ISSUE TITLE
unable to sign transaction using ledger wallet and ledgerlive

### ISSUE THREAD

**Issue by lightyear15** [urbit/bridge#1038]
Whether I try to Initialize network keys or edit management key, when it comes to generate and sign the transaction I get a ``request not supported`` error message

**To Reproduce**
Using ledger and ledger live 2.44.0 after successfully connecting my wallet to the bridge and accessing my ship ( bridge page is showing my ship, my wallet address, my current balance) when landing on the ``Initialize Network Keys``; click ``Set Network Keys``.

**Screenshot**
This is the screenshot of the erro message printed on screen
![image](https://user-images.githubusercontent.com/12190670/180475555-83631e2e-d79c-4deb-ae48-633f475d3251.png)

**Error message in browser console**
```
useEthereumTransaction.js:157 error signing txs Error: Request not supported
    at react-dom.production.min.js:67:23
    at Array.forEach (<anonymous>)
    at e.value (react-dom.production.min.js:65:19)
    at n.<anonymous> (index.ts:985:26)
    at c (bn.js:63:40)
    at Generator._invoke (bn.js:294:22)
    at Generator.next (bn.js:119:21)
    at r (asyncToGenerator.js:3:20)
    at o (asyncToGenerator.js:25:9)
(anonymous) @ useEthereumTransaction.js:157
useEthereumTransaction.js:68 Error: Request not supported
    at react-dom.production.min.js:67:23
    at Array.forEach (<anonymous>)
    at e.value (react-dom.production.min.js:65:19)
    at n.<anonymous> (index.ts:985:26)
    at c (bn.js:63:40)
    at Generator._invoke (bn.js:294:22)
    at Generator.next (bn.js:119:21)
    at r (asyncToGenerator.js:3:20)
    at o (asyncToGenerator.js:25:9)
```
**Environment**
Running on Chrome browser in ubuntu 20.04 OS

**Comment by lightyear15** [comment]
It seems this is closely connected to #1006. An issue that has been closed even if the PR that apparently was supposed to fix it is still open and not merged, right?
I mean, walletconnect/client is still at version 1.7.1, the fix is to upgrade to version 1.7.5

**Comment by ahlmark** [comment]
I am experiencing this same issue. Same parameters and same errors in console. Any resolution to this?

**Comment by ahlmark** [comment]
> I am experiencing this same issue. Same parameters and same errors in console. Any resolution to this?

My console for reference..
<img width="464" alt="Bridge Console Error" src="https://user-images.githubusercontent.com/6644988/192334669-e6e69db2-e9cc-4945-b235-41c29af27420.png">
