### ISSUE TITLE
Error Report: no urbit wallet found

### ISSUE THREAD

**Issue by cyclomancer** [urbit/bridge#1045]
I get this error when trying to retrieve my xpub for the Bitcoin wallet and logging into Bridge with MetaMask:

```
Error: no urbit wallet found
    at Object.Nothing (https://bridge.urbit.org/static/js/main.160ab69c.chunk.js:1:308400)
    at b.matchWith (https://bridge.urbit.org/static/js/2.256267e8.chunk.js:2:495817)
    at Object.<anonymous> (https://bridge.urbit.org/static/js/main.160ab69c.chunk.js:1:308092)
    at https://bridge.urbit.org/static/js/main.160ab69c.chunk.js:1:279242
    at rs (https://bridge.urbit.org/static/js/2.256267e8.chunk.js:2:3249848)
    at Qo (https://bridge.urbit.org/static/js/2.256267e8.chunk.js:2:3302306)
    at xl (https://bridge.urbit.org/static/js/2.256267e8.chunk.js:2:3289480)
    at Sl (https://bridge.urbit.org/static/js/2.256267e8.chunk.js:2:3289408)
    at Il (https://bridge.urbit.org/static/js/2.256267e8.chunk.js:2:3289271)
    at hl (https://bridge.urbit.org/static/js/2.256267e8.chunk.js:2:3286237)
```

In Bridge version 3.1.0.

**Comment by hjorthjort** [comment]
Same here, but logging into brigde the usual way (via https://bridge.urbit.org/) works. It's the link from the Bitcoin app (https://bridge.urbit.org/?kind=xpub) that borks. And I can't find any derived xpub in the usual interface. Guessing the support for it is lost from the Bridge frontend, but the Bitcoin app has not been updated.

**Comment by thelifeandtimes** [comment]
Closing this as the %bitcoin desk is deprecated and bridge no longer supports this functionality. flagging @hanfel-dovned / @bonbud-macryg / @polwex for vis as Groundwire Foundation may be picking up urbit<>bitcoin related functionality and find this worth looking at.
