### ISSUE TITLE
Logging in with two master tickets throws error

### ISSUE THREAD

**Issue by philipcmonk** [urbit/bridge#1048]
## Context

When you log in with a master ticket, then log out and try to log in with a different one, you get this error until you refresh.

## Error

```
TypeError: Cannot read properties of undefined (reading 'value')
    at https://bridge.urbit.org/static/js/main.160ab69c.chunk.js:1:240359
    at rs (https://bridge.urbit.org/static/js/2.256267e8.chunk.js:2:3249848)
    at qs (https://bridge.urbit.org/static/js/2.256267e8.chunk.js:2:3259415)
    at Qo (https://bridge.urbit.org/static/js/2.256267e8.chunk.js:2:3303297)
    at xl (https://bridge.urbit.org/static/js/2.256267e8.chunk.js:2:3289480)
    at Sl (https://bridge.urbit.org/static/js/2.256267e8.chunk.js:2:3289408)
    at Il (https://bridge.urbit.org/static/js/2.256267e8.chunk.js:2:3289271)
    at hl (https://bridge.urbit.org/static/js/2.256267e8.chunk.js:2:3286237)
    at https://bridge.urbit.org/static/js/2.256267e8.chunk.js:2:3235616
    at t.unstable_runWithPriority (https://bridge.urbit.org/static/js/2.256267e8.chunk.js:2:3313035)
```

In Bridge version 3.1.0.

**Comment by matildepark** [comment]
I believe this is not specific to master tickets; logging out and back in gives this error no matter the method.
