### ISSUE TITLE
Error Report: Cannot read properties of undefined (reading 'value')

### ISSUE THREAD

**Issue by tiller-tolbus** [urbit/bridge#1092]
## Context

Logging in with Master Ticket

Ox 9381afaFDb9FDacc9C1811ED33cD3d534A57a4e

## Error

```
TypeError: Cannot read properties of undefined (reading 'value')
    at Point (https://bridge.urbit.org/assets/index.c6214be6.js:5502:70180)
    at Ch$1 (https://bridge.urbit.org/assets/index.c6214be6.js:35:57658)
    at li (https://bridge.urbit.org/assets/index.c6214be6.js:35:68126)
    at ck (https://bridge.urbit.org/assets/index.c6214be6.js:39:10693)
    at bk (https://bridge.urbit.org/assets/index.c6214be6.js:39:1039)
    at ak (https://bridge.urbit.org/assets/index.c6214be6.js:39:962)
    at Tj (https://bridge.urbit.org/assets/index.c6214be6.js:39:803)
    at Lj (https://bridge.urbit.org/assets/index.c6214be6.js:37:11942)
    at https://bridge.urbit.org/assets/index.c6214be6.js:35:41791
    at et.unstable_runWithPriority (https://bridge.urbit.org/assets/index.c6214be6.js:24:4130)
```

In Bridge version 3.2.4.

**Comment by tomholford** [comment]
@tiller-tolbus Thanks for flagging. Which OS and browser? What flow triggered this err?

**Comment by vvisigoth** [comment]
@tiller-tolbus do you remember what the context of this was?
