### ISSUE TITLE
Error Report: Cannot read properties of undefined (reading 'value')

### ISSUE THREAD

**Issue by jee-mj** [urbit/bridge#1105]
## Context

Just trying to recover my id using master ticket.

not comfortable.

## Error

```
TypeError: Cannot read properties of undefined (reading 'value')
    at Point (https://bridge.urbit.org/assets/index.c6214be6.js:5502:70180)
    at Ch$1 (https://bridge.urbit.org/assets/index.c6214be6.js:35:57658)
    at li (https://bridge.urbit.org/assets/index.c6214be6.js:35:68126)
    at ck (https://bridge.urbit.org/assets/index.c6214be6.js:39:10693)
    at bk (https://bridge.urbit.org/assets/index.c6214be6.js:39:1039)
    at ak (https://bridge.urbit.org/assets/index.c6214be6.js:39:962)
    at Tj (https://bridge.urbit.org/assets/index.c6214be6.js:39:803)
    at Lj (https://bridge.urbit.org/assets/index.c6214be6.js:37:11942)
    at https://bridge.urbit.org/assets/index.c6214be6.js:35:41791
    at et.unstable_runWithPriority (https://bridge.urbit.org/assets/index.c6214be6.js:24:4130)
```

In Bridge version 3.2.4.

**Comment by shawntobin** [comment]
Closing since this was hopefully fixed with #1125
