### ISSUE TITLE
Second master ticket login always fails

### ISSUE THREAD

**Issue by shawntobin** [urbit/bridge#1123]
## Context

Bridge throws an error any time you try to log in via master ticket, if you've just logged out from a session which used a different master ticket.

To recreate - log in with master ticket, log out, and try to log in with another master ticket.

## Error

```
TypeError: Cannot read properties of undefined (reading 'value')
    at Point (https://bridge.urbit.org/assets/index.4e328254.js:4957:157227)
    at Ch$1 (https://bridge.urbit.org/assets/index.4e328254.js:35:57696)
    at li (https://bridge.urbit.org/assets/index.4e328254.js:35:68166)
    at ck (https://bridge.urbit.org/assets/index.4e328254.js:39:10731)
    at bk (https://bridge.urbit.org/assets/index.4e328254.js:39:1041)
    at ak (https://bridge.urbit.org/assets/index.4e328254.js:39:964)
    at Tj (https://bridge.urbit.org/assets/index.4e328254.js:39:805)
    at Lj (https://bridge.urbit.org/assets/index.4e328254.js:37:11984)
    at https://bridge.urbit.org/assets/index.4e328254.js:35:41837
    at Bt.unstable_runWithPriority (https://bridge.urbit.org/assets/index.4e328254.js:24:4130)
```

In Bridge version 3.2.8.

**Comment by shawntobin** [comment]
fixed by #1125
