### ISSUE TITLE
Error Report: Please pass numbers as strings or BigNumber objects to avoid precision errors.

### ISSUE THREAD

**Issue by narner** [urbit/bridge#318]
## Context

Setting up Urbit from an invite code

## Error

```
Error: Please pass numbers as strings or BigNumber objects to avoid precision errors.
    at fromWei (https://bridge.urbit.org/static/js/2.d800b7cb.chunk.js:1:140998)
    at kn (https://bridge.urbit.org/static/js/main.d93cb87c.chunk.js:1:123676)
    at Na (https://bridge.urbit.org/static/js/2.d800b7cb.chunk.js:1:1561481)
    at Go (https://bridge.urbit.org/static/js/2.d800b7cb.chunk.js:1:1604573)
    at Fo (https://bridge.urbit.org/static/js/2.d800b7cb.chunk.js:1:1590296)
    at qo (https://bridge.urbit.org/static/js/2.d800b7cb.chunk.js:1:1587316)
    at Lo (https://bridge.urbit.org/static/js/2.d800b7cb.chunk.js:1:1585876)
    at https://bridge.urbit.org/static/js/2.d800b7cb.chunk.js:1:1547777
    at t.unstable_runWithPriority (https://bridge.urbit.org/static/js/2.d800b7cb.chunk.js:1:1622220)
    at pi (https://bridge.urbit.org/static/js/2.d800b7cb.chunk.js:1:1547506)
```

**Comment by Fang-** [comment]
Closing, as #321 was deployed and should have fixed this.
