### ISSUE TITLE
Error Report: Please pass numbers as strings or BigNumber objects to avoid precision errors.

### ISSUE THREAD

**Issue by davis68** [urbit/bridge#323]
## Context

I was attempting to reticket a planet as part of a personal breach.

## Error

```
Error: Please pass numbers as strings or BigNumber objects to avoid precision errors.
    at fromWei (https://bridge.urbit.org/static/js/2.d800b7cb.chunk.js:1:140998)
    at kn (https://bridge.urbit.org/static/js/main.d93cb87c.chunk.js:1:123676)
    at Na (https://bridge.urbit.org/static/js/2.d800b7cb.chunk.js:1:1561481)
    at Go (https://bridge.urbit.org/static/js/2.d800b7cb.chunk.js:1:1604573)
    at Fo (https://bridge.urbit.org/static/js/2.d800b7cb.chunk.js:1:1590296)
    at qo (https://bridge.urbit.org/static/js/2.d800b7cb.chunk.js:1:1587316)
    at Lo (https://bridge.urbit.org/static/js/2.d800b7cb.chunk.js:1:1585876)
    at https://bridge.urbit.org/static/js/2.d800b7cb.chunk.js:1:1547777
    at t.unstable_runWithPriority (https://bridge.urbit.org/static/js/2.d800b7cb.chunk.js:1:1622220)
    at pi (https://bridge.urbit.org/static/js/2.d800b7cb.chunk.js:1:1547506)
```

**Comment by davis68** [comment]
You have duplicates, I see now (and I realize this step wasn't necessary for what I want to do).

**Comment by Fang-** [comment]
Thanks for filing anyway! Using metamask, I'd guess? (:

**Comment by davis68** [comment]
No, this was with a conventional master ticket login (which is why I didn't need to do it and didn't bother once it failed).

**Comment by Fang-** [comment]
Interesting. Would you mind sharing the name of the planet? (I'm not good enough to tell from your sigil. (: )

**Comment by davis68** [comment]
~hanrep-dovres

**Comment by Fang-** [comment]
Alright, nothing seems to be out of the ordinary here (aside from the error from your report, of course). Thanks for your time!
