### ISSUE TITLE
Navigation after key configuration is fragile

### ISSUE THREAD

**Issue by matildepark** [urbit/bridge#332]
## Context

Setting networking keys on a fresh point. 

## Error

```
TypeError: pattern[name] is not a function
    at InternalConstructor.matchWith (https://bridge.urbit.org/static/js/2.2db17f4c.chunk.js:60528:29)
    at Object.Just (https://bridge.urbit.org/static/js/main.02d4a6bb.chunk.js:1774:2465)
    at InternalConstructor.matchWith (https://bridge.urbit.org/static/js/2.2db17f4c.chunk.js:60528:29)
    at renderNetworkKeysDetail (https://bridge.urbit.org/static/js/main.02d4a6bb.chunk.js:1774:2338)
    at AdminEditPermissions (https://bridge.urbit.org/static/js/main.02d4a6bb.chunk.js:1774:3433)
    at dh (https://bridge.urbit.org/static/js/2.2db17f4c.chunk.js:158587:7)
    at mj (https://bridge.urbit.org/static/js/2.2db17f4c.chunk.js:161279:11)
    at jj (https://bridge.urbit.org/static/js/2.2db17f4c.chunk.js:160324:11)
    at Z (https://bridge.urbit.org/static/js/2.2db17f4c.chunk.js:160181:15)
    at $i (https://bridge.urbit.org/static/js/2.2db17f4c.chunk.js:160040:16)
```

In Bridge version 2.0.0-beta-m-191105-2.

**Comment by Fang-** [comment]
Hmm, cannot reproduce. I assume this was when viewing the permissions page (ie directly after clicking "edit permissions")?

**Comment by matildepark** [comment]
Point had no networking keys. I gave it a hexdump and it set them. I downloaded the keyfile. Hitting “Return” gave me that.

— 
~haddef-sigwen
http://urbit.org

**Comment by Fang-** [comment]
Ah, that's useful. I imagine the "custom key" path there is underutilized. I can, uh, reproduce a different error at least. Will get this sorted!

**Comment by Fang-** [comment]
Still can't reproduce after fixing the other error. ):

**Comment by vvisigoth** [comment]
Do you have any further recommendations on a repro @matildepark ?

**Comment by matildepark** [comment]
I don’t, I’m afraid. Apologies for this being so elusive.

**Comment by Fang-** [comment]
For additional contexts and other cases, see all of #419, #447, #452, #469.

**Comment by lukestiles** [comment]
No reliable reproduction, and similar issues have been closed.
