### ISSUE TITLE
Error Report: pattern[name] is not a function

### ISSUE THREAD

**Issue by hrharder** [urbit/bridge#348]
## Context

Attempting to regenerate networking keys and perform a continuity breach, I signed and submitted the Ethereum transaction via bridge, and it showed me the confirmation screen, but with no keys and no option to download. The auto caught exception is below, as well as a screenshot I took. 

![Screen Shot 2019-12-05 at 6 15 09 PM](https://user-images.githubusercontent.com/7064243/70290036-7f308280-178b-11ea-828c-46896a735778.png)

## Error

```
TypeError: pattern[name] is not a function
    at InternalConstructor.matchWith (https://bridge.urbit.org/static/js/2.a57fa0c4.chunk.js:60552:29)
    at Object.Just (https://bridge.urbit.org/static/js/main.dd87cb54.chunk.js:1769:2465)
    at InternalConstructor.matchWith (https://bridge.urbit.org/static/js/2.a57fa0c4.chunk.js:60552:29)
    at renderNetworkKeysDetail (https://bridge.urbit.org/static/js/main.dd87cb54.chunk.js:1769:2338)
    at AdminEditPermissions (https://bridge.urbit.org/static/js/main.dd87cb54.chunk.js:1769:3433)
    at dh (https://bridge.urbit.org/static/js/2.a57fa0c4.chunk.js:158610:7)
    at mj (https://bridge.urbit.org/static/js/2.a57fa0c4.chunk.js:161302:11)
    at jj (https://bridge.urbit.org/static/js/2.a57fa0c4.chunk.js:160347:11)
    at Z (https://bridge.urbit.org/static/js/2.a57fa0c4.chunk.js:160204:15)
    at $i (https://bridge.urbit.org/static/js/2.a57fa0c4.chunk.js:160063:16)
```

In Bridge version 2.0.0-beta-m-191108-1.

**Comment by hrharder** [comment]
It did work upon reloading and retrying.
