### ISSUE TITLE
Error Report: no point found

### ISSUE THREAD

**Issue by matildepark** [urbit/bridge#356]
## Reproduction steps

1. Sign in with Metamask, with any wallet that owns no points
2. Press "View a Point" at bottom

## Error

```
Error: no point found
    at Object.Nothing (https://bridge.urbit.org/static/js/main.b38e0c4e.chunk.js:1:146991)
    at g.matchWith (https://bridge.urbit.org/static/js/2.047a22a0.chunk.js:1:583313)
    at https://bridge.urbit.org/static/js/main.b38e0c4e.chunk.js:1:146645
    at https://bridge.urbit.org/static/js/main.b38e0c4e.chunk.js:1:256541
    at Na (https://bridge.urbit.org/static/js/2.047a22a0.chunk.js:1:1626006)
    at Go (https://bridge.urbit.org/static/js/2.047a22a0.chunk.js:1:1669098)
    at Fo (https://bridge.urbit.org/static/js/2.047a22a0.chunk.js:1:1654821)
    at qo (https://bridge.urbit.org/static/js/2.047a22a0.chunk.js:1:1651841)
    at $o (https://bridge.urbit.org/static/js/2.047a22a0.chunk.js:1:1650401)
    at https://bridge.urbit.org/static/js/2.047a22a0.chunk.js:1:1612302
```

In Bridge version 2.1.3.

**Comment by Fang-** [comment]
View point page is known broken iirc. I thought we took it out? It's to be replaced by whatever will become of "network explorer", at least.
