### ISSUE TITLE
Error Report: Cannot read property 'toString' of undefined

### ISSUE THREAD

**Issue by cwervo** [urbit/bridge#382]
## Context

This was after step 2, where it said "this may take up to 5 minutes". I returned to the tab & found the error below.

## Error

```
TypeError: Cannot read property 'toString' of undefined
    at renderAdditionalInfo (https://bridge.urbit.org/static/js/main.c52f9a57.chunk.js:2224:588)
    at PassportTransfer (https://bridge.urbit.org/static/js/main.c52f9a57.chunk.js:2224:1821)
    at dh (https://bridge.urbit.org/static/js/2.3deee14d.chunk.js:159000:7)
    at Jh (https://bridge.urbit.org/static/js/2.3deee14d.chunk.js:159476:7)
    at mj (https://bridge.urbit.org/static/js/2.3deee14d.chunk.js:161749:86)
    at jj (https://bridge.urbit.org/static/js/2.3deee14d.chunk.js:160737:11)
    at Z (https://bridge.urbit.org/static/js/2.3deee14d.chunk.js:160594:15)
    at $i (https://bridge.urbit.org/static/js/2.3deee14d.chunk.js:160453:16)
    at https://bridge.urbit.org/static/js/2.3deee14d.chunk.js:158179:17
    at push.exports.unstable_runWithPriority (https://bridge.urbit.org/static/js/2.3deee14d.chunk.js:162874:12)
```

In Bridge version 2.3.1.

**Comment by Fang-** [comment]
This is an error during error display! I'm able to reproduce this though, and working on fixing both these issues right now.

I suspect the passport you generated & downloaded should work fine though. Can you confirm?

**Comment by cwervo** [comment]
Unfortunately the passport I got didn't/still doesn't allow me to sign in to Bridge, but I was able to get another invite.

**Comment by Fang-** [comment]
Hmm, if the passport you downloaded didn't work, then I assume the invite you used originally still worked? Did you try that? If not, can you confirm if it's still usable?
