### ISSUE TITLE
Error Report: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Bticket%2C%20signedTx%2C%20rawTx%7D&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 

### ISSUE THREAD

**Issue by tomson189** [urbit/bridge#414]
## Context

Error occured while generating invite URL 

## Error

```
Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Bticket%2C%20signedTx%2C%20rawTx%7D&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
    at mg (https://bridge.urbit.org/static/js/2.9ed8dd63.chunk.js:158621:38)
    at z (https://bridge.urbit.org/static/js/2.9ed8dd63.chunk.js:158715:7)
    at rb (https://bridge.urbit.org/static/js/2.9ed8dd63.chunk.js:158781:13)
    at https://bridge.urbit.org/static/js/2.9ed8dd63.chunk.js:158898:23
    at S (https://bridge.urbit.org/static/js/2.9ed8dd63.chunk.js:159470:26)
    at mj (https://bridge.urbit.org/static/js/2.9ed8dd63.chunk.js:161811:306)
    at jj (https://bridge.urbit.org/static/js/2.9ed8dd63.chunk.js:160777:11)
    at Z (https://bridge.urbit.org/static/js/2.9ed8dd63.chunk.js:160634:15)
    at $i (https://bridge.urbit.org/static/js/2.9ed8dd63.chunk.js:160493:16)
    at https://bridge.urbit.org/static/js/2.9ed8dd63.chunk.js:158219:17
```

In Bridge version 2.3.5.

**Comment by Fang-** [comment]
Closing in favor of #418. Thanks for filing!
