### ISSUE TITLE
Error Report: Cannot create property 'message' on string 'Node error: {"code":-32000,"message":"nonce too low"}'

### ISSUE THREAD

**Issue by ixv** [urbit/bridge#422]
Got this while trying to verify a master ticket from an invite code.

## Error

```
TypeError: Cannot create property 'message' on string 'Node error: {"code":-32000,"message":"nonce too low"}'
    at renderAdditionalInfo (https://bridge.urbit.org/static/js/main.21612c58.chunk.js:2261:385)
    at PassportTransfer (https://bridge.urbit.org/static/js/main.21612c58.chunk.js:2261:1914)
    at dh (https://bridge.urbit.org/static/js/2.9ed8dd63.chunk.js:159040:7)
    at Jh (https://bridge.urbit.org/static/js/2.9ed8dd63.chunk.js:159516:7)
    at mj (https://bridge.urbit.org/static/js/2.9ed8dd63.chunk.js:161789:86)
    at jj (https://bridge.urbit.org/static/js/2.9ed8dd63.chunk.js:160777:11)
    at Z (https://bridge.urbit.org/static/js/2.9ed8dd63.chunk.js:160634:15)
    at $i (https://bridge.urbit.org/static/js/2.9ed8dd63.chunk.js:160493:16)
    at https://bridge.urbit.org/static/js/2.9ed8dd63.chunk.js:158219:17
    at push.exports.unstable_runWithPriority (https://bridge.urbit.org/static/js/2.9ed8dd63.chunk.js:162914:12)
```

In Bridge version 2.3.5.

**Comment by liam-fitzgerald** [comment]
@Fang- nonce is usually gas tank shenanigans can you check?

**Comment by Fang-** [comment]
Looks like the error printing logic in `renderAdditionalInfo` (in both `PassportTransfer` and `ResetExecute`) doesn't account for the case where `generalError` is a string rather than an object.

That said, the error that was trying to get printed should have been caught if we made use of the gas tank, and shouldn't occur if we didn't.

The context is weird, too. @ixv you got this during the verification step, or directly after, when it's telling you to wait for a bit?

**Comment by liam-fitzgerald** [comment]
Have looked into this further.. web3.js errors should be cast to a string [here](https://github.com/ethereum/web3.js/blob/c20bcf09b04f773406ce3532e88fd105bb04e244/packages/web3-utils/src/index.js#L56), but it's throwing a string?  I suspected we had a reoccurence of the dreaded toWei errors ( #410 ) because underscore uses the constructor to test for stringiness. But, webpack doesn't mangle native constructors. So uhh what do you think @Fang- ?

**Comment by Fang-** [comment]
I think it wouldn't be a problem for us to just support the "error is a string" case and call it a day.
