### ISSUE TITLE
Error Report: sigil.js cannot render @p of length 16. Only lengths of 1 (galaxy), 2 (star), and 4 (planet) are supported at this time.

### ISSUE THREAD

**Issue by ekbyang** [urbit/bridge#453]
## Context

I was trying to enter my comet ID

## Error

```
Error: sigil.js cannot render @p of length 16. Only lengths of 1 (galaxy), 2 (star), and 4 (planet) are supported at this time.
    at sigil (https://bridge.urbit.org/static/js/2.9ed8dd63.chunk.js:56264:11)
    at Sigil (https://bridge.urbit.org/static/js/main.21612c58.chunk.js:208:1305)
    at dh (https://bridge.urbit.org/static/js/2.9ed8dd63.chunk.js:159040:7)
    at mj (https://bridge.urbit.org/static/js/2.9ed8dd63.chunk.js:161732:11)
    at jj (https://bridge.urbit.org/static/js/2.9ed8dd63.chunk.js:160777:11)
    at Z (https://bridge.urbit.org/static/js/2.9ed8dd63.chunk.js:160634:15)
    at $i (https://bridge.urbit.org/static/js/2.9ed8dd63.chunk.js:160493:16)
    at https://bridge.urbit.org/static/js/2.9ed8dd63.chunk.js:158219:17
    at push.exports.unstable_runWithPriority (https://bridge.urbit.org/static/js/2.9ed8dd63.chunk.js:162914:12)
    at vf (https://bridge.urbit.org/static/js/2.9ed8dd63.chunk.js:158189:10)
```

In Bridge version 2.3.5.

**Comment by Fang-** [comment]
Well, comets don't exist on Azimuth, and as such aren't supported by Bridge. 

We shouldn't be crashing on this though! Closing this in favor of the identical issue, #344, but thank you for reporting this! (:
