### ISSUE TITLE
Shouldn't pass objects as errors to final-form

### ISSUE THREAD

**Issue by HalifaxShadow** [urbit/bridge#455]
## Context

I had just verified transaction for sending an email invitation for a planet 

I was waiting for the "Sending Invitation" action to complete, and this problem spontaneously occurred.  It happened several times.  I am unable to send an email invitation.

## Error

`Objects are not valid as a React child (found: object with keys {ticket, signedTx, rawTx}). If you meant to render a collection of children, use an array instead.`

```
Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Bticket%2C%20signedTx%2C%20rawTx%7D&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
    at mg (https://bridge.urbit.org/static/js/2.9ed8dd63.chunk.js:158621:38)
    at z (https://bridge.urbit.org/static/js/2.9ed8dd63.chunk.js:158715:7)
    at rb (https://bridge.urbit.org/static/js/2.9ed8dd63.chunk.js:158781:13)
    at https://bridge.urbit.org/static/js/2.9ed8dd63.chunk.js:158898:23
    at S (https://bridge.urbit.org/static/js/2.9ed8dd63.chunk.js:159470:26)
    at mj (https://bridge.urbit.org/static/js/2.9ed8dd63.chunk.js:161811:306)
    at jj (https://bridge.urbit.org/static/js/2.9ed8dd63.chunk.js:160777:11)
    at Z (https://bridge.urbit.org/static/js/2.9ed8dd63.chunk.js:160634:15)
    at $i (https://bridge.urbit.org/static/js/2.9ed8dd63.chunk.js:160493:16)
    at https://bridge.urbit.org/static/js/2.9ed8dd63.chunk.js:158219:17
```

In Bridge version 2.3.5.

**Comment by HalifaxShadow** [comment]
OK this also occurs after verifying transaction for creating a URL invitation

Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Bticket%2C%20signedTx%2C%20rawTx%7D&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
    at mg (https://bridge.urbit.org/static/js/2.9ed8dd63.chunk.js:158621:38)
    at z (https://bridge.urbit.org/static/js/2.9ed8dd63.chunk.js:158715:7)
    at rb (https://bridge.urbit.org/static/js/2.9ed8dd63.chunk.js:158781:13)
    at https://bridge.urbit.org/static/js/2.9ed8dd63.chunk.js:158898:23
    at S (https://bridge.urbit.org/static/js/2.9ed8dd63.chunk.js:159470:26)
    at mj (https://bridge.urbit.org/static/js/2.9ed8dd63.chunk.js:161811:306)
    at jj (https://bridge.urbit.org/static/js/2.9ed8dd63.chunk.js:160777:11)
    at Z (https://bridge.urbit.org/static/js/2.9ed8dd63.chunk.js:160634:15)
    at $i (https://bridge.urbit.org/static/js/2.9ed8dd63.chunk.js:160493:16)

**Comment by Fang-** [comment]
@liam-fitzgerald I looked around a bit and think it might be this?

https://github.com/urbit/bridge/blob/master/src/lib/useInviter.js#L185

Those `unsentInvites` come from here:

https://github.com/urbit/bridge/blob/master/src/lib/useInviter.js#L134

which matches the description of the keys in the error message.

I guess final-forms expects form errors to always be strings? We should serialize these here then, right? Probably want to include email addresses etc so the user knows which ones didn't get sent, if it was a partial failure.
