### ISSUE TITLE
Error Report: Cannot create property 'message' on string 'Node error: {"code":-32000,"message":"nonce too low"}'

### ISSUE THREAD

**Issue by gorlandodb** [urbit/bridge#462]
## Error

```
TypeError: Cannot create property 'message' on string 'Node error: {"code":-32000,"message":"nonce too low"}'
    at renderAdditionalInfo (https://bridge.urbit.org/static/js/main.57d78efe.chunk.js:2405:385)
    at PassportTransfer (https://bridge.urbit.org/static/js/main.57d78efe.chunk.js:2405:1914)
    at dh (https://bridge.urbit.org/static/js/2.c81577b1.chunk.js:159043:7)
    at Jh (https://bridge.urbit.org/static/js/2.c81577b1.chunk.js:159519:7)
    at mj (https://bridge.urbit.org/static/js/2.c81577b1.chunk.js:161792:86)
    at jj (https://bridge.urbit.org/static/js/2.c81577b1.chunk.js:160780:11)
    at Z (https://bridge.urbit.org/static/js/2.c81577b1.chunk.js:160637:15)
    at $i (https://bridge.urbit.org/static/js/2.c81577b1.chunk.js:160496:16)
    at https://bridge.urbit.org/static/js/2.c81577b1.chunk.js:158222:17
    at push.exports.unstable_runWithPriority (https://bridge.urbit.org/static/js/2.c81577b1.chunk.js:162917:12)
```

In Bridge version 2.4.1.

**Comment by Fang-** [comment]
Closing in favor of #473. Thanks for reporting, in any case!
