### ISSUE TITLE
Error Report: Cannot read property 'data' of undefined

### ISSUE THREAD

**Issue by robert-sherwood** [urbit/bridge#463]
## Context

I pressed logout immediately after completing a transfer of ownership for my planet

~tillys-fasryp

## Error

```
TypeError: Cannot read property 'data' of undefined
    at https://bridge.urbit.org/static/js/main.57d78efe.chunk.js:1356:911
    at Object.useMemo (https://bridge.urbit.org/static/js/2.c81577b1.chunk.js:159372:9)
    at useMemo (https://bridge.urbit.org/static/js/2.c81577b1.chunk.js:155587:16)
    at useRouter (https://bridge.urbit.org/static/js/main.57d78efe.chunk.js:1356:862)
    at Admin (https://bridge.urbit.org/static/js/main.57d78efe.chunk.js:2158:1134)
    at dh (https://bridge.urbit.org/static/js/2.c81577b1.chunk.js:159043:7)
    at Jh (https://bridge.urbit.org/static/js/2.c81577b1.chunk.js:159519:7)
    at mj (https://bridge.urbit.org/static/js/2.c81577b1.chunk.js:161792:86)
    at jj (https://bridge.urbit.org/static/js/2.c81577b1.chunk.js:160780:11)
    at Z (https://bridge.urbit.org/static/js/2.c81577b1.chunk.js:160637:15)
```

In Bridge version 2.4.1.

**Comment by Fang-** [comment]
Maybe similar to #332.
