### ISSUE TITLE
Error Report: Cannot create property 'message' on string 'already known'

### ISSUE THREAD

**Issue by gptix** [urbit/bridge#514]
## Context

tew

 trying to register an urbit planet

## Error

```
TypeError: Cannot create property 'message' on string 'already known'
    at renderAdditionalInfo (https://bridge.urbit.live/static/js/main.b6a701ac.chunk.js:2322:385)
    at PassportTransfer (https://bridge.urbit.live/static/js/main.b6a701ac.chunk.js:2322:1914)
    at dh (https://bridge.urbit.live/static/js/2.a3f8391b.chunk.js:159072:7)
    at Jh (https://bridge.urbit.live/static/js/2.a3f8391b.chunk.js:159548:7)
    at mj (https://bridge.urbit.live/static/js/2.a3f8391b.chunk.js:161821:86)
    at jj (https://bridge.urbit.live/static/js/2.a3f8391b.chunk.js:160809:11)
    at Z (https://bridge.urbit.live/static/js/2.a3f8391b.chunk.js:160666:15)
    at $i (https://bridge.urbit.live/static/js/2.a3f8391b.chunk.js:160525:16)
    at https://bridge.urbit.live/static/js/2.a3f8391b.chunk.js:158251:17
    at push.exports.unstable_runWithPriority (https://bridge.urbit.live/static/js/2.a3f8391b.chunk.js:162946:12)
```

In Bridge version 2.5.0.

**Comment by Fang-** [comment]
>version 2.5.0

This specific error should be fixed in the latest version (v2.5.5) of Bridge. Try [bridge.urbit.org](https://bridge.urbit.org/).

Could be that the registering did succeed under the hood. But if logging in with the master ticket you downloaded doesn't work, you can just register the planet again using the same invite code.
