### ISSUE TITLE
Error Report: Cannot read property 'map' of null

### ISSUE THREAD

**Issue by Quaternioneer** [urbit/bridge#531]
1) I transferred  a planet from one Ethereum  address to my hardware wallet address. 

2) I transferred a second planet to my hardware wallet address. Then when I attempted to log into bridge as this planet I received the following error. Now I cannot log into bridge as either planet.

## Error

```
TypeError: Cannot read property 'map' of null
    at Object.Ok (https://bridge.urbit.org/static/js/main.54441b0b.chunk.js:1:224606)
    at g.matchWith (https://bridge.urbit.org/static/js/2.d3ac7638.chunk.js:1:523939)
    at https://bridge.urbit.org/static/js/main.54441b0b.chunk.js:1:224530
    at g.Just [as chain] (https://bridge.urbit.org/static/js/2.d3ac7638.chunk.js:1:613207)
    at https://bridge.urbit.org/static/js/main.54441b0b.chunk.js:1:224519
    at Object.ys [as useMemo] (https://bridge.urbit.org/static/js/2.d3ac7638.chunk.js:1:1802321)
    at t.useMemo (https://bridge.urbit.org/static/js/2.d3ac7638.chunk.js:1:1740321)
    at [POINTS] (https://bridge.urbit.org/static/js/main.54441b0b.chunk.js:1:224512)
    at Wa (https://bridge.urbit.org/static/js/2.d3ac7638.chunk.js:1:1798655)
    at Bs (https://bridge.urbit.org/static/js/2.d3ac7638.chunk.js:1:1807543)
```

In Bridge version 2.5.9.

**Comment by Quaternioneer** [comment]
I forgot for a moment that only a subset of Urbit is on ethereum, and Urbit could move to another blockchain if necessary. So, isn't as serious as it seemed at first blush.

**Comment by Fang-** [comment]
Hey @Quaternioneer. Sorry for not responding sooner!

I tried reproducing this, but couldn't get it to error out. Judging from the stack trace, I think I know where the error occurred, but can't see a way for that result to be `null`. Might be a problem way down at the `web3` level, it giving `null` as a result of running this query, somehow?

Looks like you got sorted, but let me know if this recurs!

**Comment by Quaternioneer** [comment]
Someone, pointed out that Bridge doesn't work with the latest Trezor firmware. I must have updated between those two steps. Sorry, I should have closed this a week or so ago.Closing now.
