### ISSUE TITLE
Error Report: Cannot read property 'map' of null

### ISSUE THREAD

**Issue by Datagrdn** [urbit/bridge#558]
## Context

Trying to log in via MetaMask

## Error

```
TypeError: Cannot read property 'map' of null
    at Object.Ok (https://bridge.urbit.org/static/js/main.b2800745.chunk.js:2263:2859)
    at InternalConstructor.matchWith (https://bridge.urbit.org/static/js/2.de79ebd6.chunk.js:33518:29)
    at https://bridge.urbit.org/static/js/main.b2800745.chunk.js:2263:2771
    at InternalConstructor.chain (https://bridge.urbit.org/static/js/2.de79ebd6.chunk.js:65133:14)
    at https://bridge.urbit.org/static/js/main.b2800745.chunk.js:2263:2750
    at Object.Mh [as useMemo] (https://bridge.urbit.org/static/js/2.de79ebd6.chunk.js:174847:7)
    at push.exports.useMemo (https://bridge.urbit.org/static/js/2.de79ebd6.chunk.js:170996:14)
    at Points (https://bridge.urbit.org/static/js/main.b2800745.chunk.js:2263:2728)
    at oh (https://bridge.urbit.org/static/js/2.de79ebd6.chunk.js:174592:7)
    at di (https://bridge.urbit.org/static/js/2.de79ebd6.chunk.js:175212:7)
```

In Bridge version 2.5.12.

**Comment by Fang-** [comment]
Might be a duplicate of #554. Could you tell me the Ethereum address you were logging in with (either here, or email to mark@tlon.io), so I can try to reproduce this?

**Comment by thelifeandtimes** [comment]
Closing out as a presumed dupe of #554.
