### ISSUE TITLE
Error Report: Cannot read property 'map' of null -- From trying to login to bridge using MetaMask.

### ISSUE THREAD

**Issue by pondeb-firden** [urbit/bridge#559]
Can't seem to login to Bridge using MetaMask.

## Context
Just trying to login to Bridge for the first time using MetaMask; previously I had signed in with my ETH private key. I accepted the connect dialog box in MetaMask, and then it errored out. I also tried rebooting Bridge and trying again, to no avail.

## Error
```
TypeError: Cannot read property 'map' of null
    at Object.Ok (https://bridge.urbit.org/static/js/main.b2800745.chunk.js:2263:2859)
    at InternalConstructor.matchWith (https://bridge.urbit.org/static/js/2.de79ebd6.chunk.js:33518:29)
    at https://bridge.urbit.org/static/js/main.b2800745.chunk.js:2263:2771
    at InternalConstructor.chain (https://bridge.urbit.org/static/js/2.de79ebd6.chunk.js:65133:14)
    at https://bridge.urbit.org/static/js/main.b2800745.chunk.js:2263:2750
    at Object.Mh [as useMemo] (https://bridge.urbit.org/static/js/2.de79ebd6.chunk.js:174847:7)
    at push.exports.useMemo (https://bridge.urbit.org/static/js/2.de79ebd6.chunk.js:170996:14)
    at Points (https://bridge.urbit.org/static/js/main.b2800745.chunk.js:2263:2728)
    at oh (https://bridge.urbit.org/static/js/2.de79ebd6.chunk.js:174592:7)
    at di (https://bridge.urbit.org/static/js/2.de79ebd6.chunk.js:175212:7)
```

In Bridge version 2.5.12.

**Comment by pondeb-firden** [comment]
looks like a dupe of #554
