### ISSUE TITLE
Error Report: no urbit wallet found

### ISSUE THREAD

**Issue by rosario3** [urbit/bridge#632]
## Error

```
Error: no urbit wallet found
    at Object.Nothing (https://bridge.urbit.org/static/js/main.2589e507.chunk.js:1:25699)
    at b.matchWith (https://bridge.urbit.org/static/js/2.c64e7708.chunk.js:2:366802)
    at https://bridge.urbit.org/static/js/main.2589e507.chunk.js:1:25391
    at https://bridge.urbit.org/static/js/main.2589e507.chunk.js:1:222298
    at rs (https://bridge.urbit.org/static/js/2.c64e7708.chunk.js:2:3663822)
    at Qo (https://bridge.urbit.org/static/js/2.c64e7708.chunk.js:2:3716280)
    at kl (https://bridge.urbit.org/static/js/2.c64e7708.chunk.js:2:3703454)
    at Sl (https://bridge.urbit.org/static/js/2.c64e7708.chunk.js:2:3703382)
    at Il (https://bridge.urbit.org/static/js/2.c64e7708.chunk.js:2:3703245)
    at hl (https://bridge.urbit.org/static/js/2.c64e7708.chunk.js:2:3700211)
```

In Bridge version 2.10.4.

**Comment by tomholford** [comment]
@rosario3 Hello, can you share some info to help diagnose the issue:

- What login method?
- What action caused this issue?

Thanks

**Comment by Fang-** [comment]
I suspect this might be a case of #586 (I don't think we use this assertion anywhere outside of the Bitcoin flows), but yes, please confirm when you get the chance.

**Comment by rosario3** [comment]
Hi Team:  This has been a while so don't remember too much details.  I did
get it to work.

login method: metamask
action that caused the issue:  logging into urbit bridge via metamask
