### ISSUE TITLE
Objects not valid as react child

### ISSUE THREAD

**Issue by mlizak** [urbit/bridge#651]
## Error

```
Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Bcode%2C%20message%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at _a (https://bridge.urbit.org/static/js/2.d15fa35e.chunk.js:2:3656012)
    at p (https://bridge.urbit.org/static/js/2.d15fa35e.chunk.js:2:3658000)
    at y (https://bridge.urbit.org/static/js/2.d15fa35e.chunk.js:2:3658537)
    at https://bridge.urbit.org/static/js/2.d15fa35e.chunk.js:2:3660820
    at Rs (https://bridge.urbit.org/static/js/2.d15fa35e.chunk.js:2:3671928)
    at Qo (https://bridge.urbit.org/static/js/2.d15fa35e.chunk.js:2:3718103)
    at kl (https://bridge.urbit.org/static/js/2.d15fa35e.chunk.js:2:3703454)
    at Sl (https://bridge.urbit.org/static/js/2.d15fa35e.chunk.js:2:3703382)
    at Il (https://bridge.urbit.org/static/js/2.d15fa35e.chunk.js:2:3703245)
    at hl (https://bridge.urbit.org/static/js/2.d15fa35e.chunk.js:2:3700211)
```

In Bridge version 2.10.5.

**Comment by Fang-** [comment]
This is probably a duplicate of (or at least similar case to) #564. @mlizak do you remember what you were doing when the error occurred?
