### ISSUE TITLE
Cannot login to brige (infura quota exceeded?)

### ISSUE THREAD

**Issue by abliss** [urbit/bridge#655]
## Context

trying to log into my galaxy with my master ticket shards. failed 2/2 tries with same error. First it said "this wallet is not the owner" and I clicked "login anyway", then got this stacktrace.

## Error

```
Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Bcode%2C%20message%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at _a (https://bridge.urbit.org/static/js/2.d15fa35e.chunk.js:2:3656012)
    at p (https://bridge.urbit.org/static/js/2.d15fa35e.chunk.js:2:3658000)
    at y (https://bridge.urbit.org/static/js/2.d15fa35e.chunk.js:2:3658537)
    at https://bridge.urbit.org/static/js/2.d15fa35e.chunk.js:2:3660820
    at Rs (https://bridge.urbit.org/static/js/2.d15fa35e.chunk.js:2:3671928)
    at Qo (https://bridge.urbit.org/static/js/2.d15fa35e.chunk.js:2:3718103)
    at kl (https://bridge.urbit.org/static/js/2.d15fa35e.chunk.js:2:3703454)
    at Sl (https://bridge.urbit.org/static/js/2.d15fa35e.chunk.js:2:3703382)
    at Il (https://bridge.urbit.org/static/js/2.d15fa35e.chunk.js:2:3703245)
    at hl (https://bridge.urbit.org/static/js/2.d15fa35e.chunk.js:2:3700211)
```

In Bridge version 2.10.5.

**Comment by abliss** [comment]
Oh, the JS console has this:

_warnOfDeprecation @ inpage.js:1
mainnet.infura.io/v3/2599df54929b47099bda360958d75aaf:1 Failed to load resource: the server responded with a status of 429 ()
Uncaught (in promise) Error: Returned error: daily request count exceeded, request rate limited
