### ISSUE TITLE
Error Report: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=folktale%3AMaybe.Nothing(%7B%20%20%7D) for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

### ISSUE THREAD

**Issue by hamdERGler** [urbit/bridge#699]
## Context

I activated a planet, have downloaded the network keys and the access code, then I clicked on 'view network keys'

## Error

```
Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=folktale%3AMaybe.Nothing(%7B%20%20%7D) for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at _a (https://bridge.urbit.org/static/js/2.d15fa35e.chunk.js:2:3656012)
    at https://bridge.urbit.org/static/js/2.d15fa35e.chunk.js:2:3660863
    at Rs (https://bridge.urbit.org/static/js/2.d15fa35e.chunk.js:2:3671913)
    at Qo (https://bridge.urbit.org/static/js/2.d15fa35e.chunk.js:2:3718103)
    at kl (https://bridge.urbit.org/static/js/2.d15fa35e.chunk.js:2:3703454)
    at Sl (https://bridge.urbit.org/static/js/2.d15fa35e.chunk.js:2:3703382)
    at Il (https://bridge.urbit.org/static/js/2.d15fa35e.chunk.js:2:3703245)
    at hl (https://bridge.urbit.org/static/js/2.d15fa35e.chunk.js:2:3700211)
    at https://bridge.urbit.org/static/js/2.d15fa35e.chunk.js:2:3649590
    at t.unstable_runWithPriority (https://bridge.urbit.org/static/js/2.d15fa35e.chunk.js:2:3727009)
```

In Bridge version 2.10.5.

**Comment by Fang-** [comment]
Thanks for filing @hamdERGler, this is useful context. Notably duplicate of #564 and #651, but I'll keep this one open because it actually describes a context. We'll look into it!

**Comment by hamdERGler** [comment]
cheers! This Eth address has a star which is the sponsor of this planet
where the error occurred.
