### ISSUE TITLE
L2 transfer: prevent galaxy transmogrification

### ISSUE THREAD

**Issue by drbeefsupreme** [urbit/bridge#707]
**Describe the bug**
An error message appears when you try to migrate a galaxy from L1 to L2. This action shouldn't be allowed, but it shouldn't crash Bridge either.

**To Reproduce**
1. Login as a galaxy
2. Click the address bar at the top
3. Click Migrate L1 -> L2
4. Click Migrate

Resulting error:

```
TypeError: Cannot read properties of undefined (reading 'point')
    at https://bridge-dev.urbit.org/static/js/main.b61f17b3.chunk.js:1:317916
    at rs (https://bridge-dev.urbit.org/static/js/2.8d0bb710.chunk.js:2:3264786)
    at Qo (https://bridge-dev.urbit.org/static/js/2.8d0bb710.chunk.js:2:3317244)
    at xl (https://bridge-dev.urbit.org/static/js/2.8d0bb710.chunk.js:2:3304418)
    at Sl (https://bridge-dev.urbit.org/static/js/2.8d0bb710.chunk.js:2:3304346)
    at Il (https://bridge-dev.urbit.org/static/js/2.8d0bb710.chunk.js:2:3304209)
    at hl (https://bridge-dev.urbit.org/static/js/2.8d0bb710.chunk.js:2:3301175)
    at https://bridge-dev.urbit.org/static/js/2.8d0bb710.chunk.js:2:3250554
    at t.unstable_runWithPriority (https://bridge-dev.urbit.org/static/js/2.8d0bb710.chunk.js:2:3327973)
    at Gi (https://bridge-dev.urbit.org/static/js/2.8d0bb710.chunk.js:2:3250331)
```

**Expected behavior**
It should tell you that this action isn't allowed rather than crashing Bridge.

**Screenshots**
https://i.imgur.com/v2AKH5H.png

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Edge

**Login method (please complete the following information):**
Master Ticket

**Additional context**
Probably very low priority.

**Comment by nerveharp** [comment]
We don't permit galaxies to move to L2.

**Comment by drbeefsupreme** [comment]
That's not what this issue is about - its about Bridge crashing when you try to do it anyways, when instead it shouldn't present it as an option at all.

**Comment by nerveharp** [comment]
Understood. Let's rephrase and address later.
