### ISSUE TITLE
Error encountered after clicking on `Transfer` on `Ownership Address`

### ISSUE THREAD

**Issue by jyng** [urbit/bridge#747]
## Context

Tried to `Transfer` Ownership Address and Bridge crashed

## Error

```
TypeError: Cannot read properties of null (reading 'kind')
    at https://bridge-dev.urbit.org/static/js/main.a823ea03.chunk.js:1:255321
    at b.Just [as map] (https://bridge-dev.urbit.org/static/js/2.2c7d63ae.chunk.js:2:1273880)
    at https://bridge-dev.urbit.org/static/js/main.a823ea03.chunk.js:1:255295
    at Object.useMemo (https://bridge-dev.urbit.org/static/js/2.2c7d63ae.chunk.js:2:3270751)
    at t.useMemo (https://bridge-dev.urbit.org/static/js/2.2c7d63ae.chunk.js:2:3205248)
    at https://bridge-dev.urbit.org/static/js/main.a823ea03.chunk.js:1:255207
    at rs (https://bridge-dev.urbit.org/static/js/2.2c7d63ae.chunk.js:2:3264786)
    at Qo (https://bridge-dev.urbit.org/static/js/2.2c7d63ae.chunk.js:2:3317244)
    at xl (https://bridge-dev.urbit.org/static/js/2.2c7d63ae.chunk.js:2:3304418)
    at Sl (https://bridge-dev.urbit.org/static/js/2.2c7d63ae.chunk.js:2:3304346)
```

In Bridge version 2.10.3r.

**Comment by willbach** [comment]
@jyng I can't reproduce this. Can you provide some details about the login method/account you used and the point your were trying to transfer?

**Comment by willbach** [comment]
Haven't seen this in a while. Can't reproduce now.
