### ISSUE TITLE
Login: various Metamask failures

### ISSUE THREAD

**Issue by nerveharp** [urbit/bridge#820]
**Describe the bug:**
Metamask login appears to throw errors 75% of the time, with the notable exception of the first-time wallet connection. I was able to create a new MM wallet (Ropsten) and sign in to Bridge, accept a planet transfer (signing with MM), set the network keys and management proxy (all MM), but when I was forced to refresh the app (which logs me out), I cannot sign back in, regardless of cache status.

**To reproduce:**
1. Create a new Metamask wallet and log in to Bridge via it (ensuring you are connected to Ropsten).
2. Perform some operations -- accept a L1/L2 planet transfer, for example.
3. Refresh the page.
4. Attempt to log in with Metamask again.
5. Depending on your cache status, one of three things may happen:

5a. You will be prompted to sign the login transaction via Metamask. Then, these errors will appear along with a gray spinner masking out the page:
```
inpage.js:1 MetaMask - RPC Error: execution reverted {code: -32000, message: 'execution reverted'}
```
```
useStarReleaseStore.js:53 error fetching star release details {code: -32000, message: 'execution reverted'}
```
5b. You will be prompted to sign the login transaction via Metamask. Then, Bridge will throw this full-page error:
```
TypeError: b.chain is not a function
    at https://bridge-dev.urbit.org/static/js/main.f71870d9.chunk.js:1:287355
    at Object.Ss [as useMemo] (https://bridge-dev.urbit.org/static/js/2.3560603a.chunk.js:2:3289132)
    at t.useMemo (https://bridge-dev.urbit.org/static/js/2.3560603a.chunk.js:2:3224861)
    at https://bridge-dev.urbit.org/static/js/main.f71870d9.chunk.js:1:287333
    at rs (https://bridge-dev.urbit.org/static/js/2.3560603a.chunk.js:2:3284399)
    at qs (https://bridge-dev.urbit.org/static/js/2.3560603a.chunk.js:2:3293966)
    at Qo (https://bridge-dev.urbit.org/static/js/2.3560603a.chunk.js:2:3337848)
    at xl (https://bridge-dev.urbit.org/static/js/2.3560603a.chunk.js:2:3324031)
    at Sl (https://bridge-dev.urbit.org/static/js/2.3560603a.chunk.js:2:3323959)
    at Il (https://bridge-dev.urbit.org/static/js/2.3560603a.chunk.js:2:3323822)
```
5c. You will not be prompted to sign the login transaction via Metamask. Clicking on the Metamask option will perform a no-op, and the same error as in (5b) will appear in the console.

**Ethereum network:**
Ropsten

**Desktop:**
 - Chromium Version 96.0.4664.45 (Official Build) Arch Linux (64-bit)

**Login method (please complete the following information):**
 - Metamask on Ropsten via address `0x004BB027151e9796DB239Af9b6C2310EAAB4BAa7`

**Comment by nerveharp** [comment]
Have not encountered any of the above failures, but still encountering a variant of step (5c) above, with this console error in both Chromium and Firefox:  

```
LoginSelector.tsx:97 Error: Returned error: The method personal_sign does not exist/is not available
    at Object.ErrorResponse (errors.js:28)
    at index.js:302
    at XMLHttpRequest.i.onreadystatechange (index.js:98)
```

First-time sign-in was a breeze, though.

**Comment by nerveharp** [comment]
These all seem to be resolved. Signing login and other transactions works via Metamask extension on Firefox and Chrome, as well as through WalletConnect on the Metamask mobile app.
