### ISSUE TITLE
Error Report: no urbit wallet found

### ISSUE THREAD

**Issue by DaxSosa** [urbit/bridge#953]
## Error

```
Error: no urbit wallet found
    at Object.Nothing (https://bridge.urbit.org/static/js/main.c02dd66f.chunk.js:1:25699)
    at b.matchWith (https://bridge.urbit.org/static/js/2.d15fa35e.chunk.js:2:366802)
    at https://bridge.urbit.org/static/js/main.c02dd66f.chunk.js:1:25391
    at https://bridge.urbit.org/static/js/main.c02dd66f.chunk.js:1:222298
    at rs (https://bridge.urbit.org/static/js/2.d15fa35e.chunk.js:2:3663822)
    at Qo (https://bridge.urbit.org/static/js/2.d15fa35e.chunk.js:2:3716280)
    at kl (https://bridge.urbit.org/static/js/2.d15fa35e.chunk.js:2:3703454)
    at Sl (https://bridge.urbit.org/static/js/2.d15fa35e.chunk.js:2:3703382)
    at Il (https://bridge.urbit.org/static/js/2.d15fa35e.chunk.js:2:3703245)
    at hl (https://bridge.urbit.org/static/js/2.d15fa35e.chunk.js:2:3700211)
```

In Bridge version 2.10.5.

**Comment by lukestiles** [comment]
Closing as not reproducible.
