### ISSUE TITLE
L2 planet claiming: "error: failed to parse" in final step

### ISSUE THREAD

**Issue by nerveharp** [urbit/bridge#962]
Console errors:

```
useKeyfileGenerator.ts:90 keys do not match details for revision 1

MasterKeyTransfer.tsx:39 Error: Failed to parse
    at new t (2.7ac53409.chunk.js:2:893797)
    at Object.t.convertJSONToRPCError (2.7ac53409.chunk.js:2:894032)
    at e.processResult (2.7ac53409.chunk.js:2:8651845)
    at e.resolveRes (2.7ac53409.chunk.js:2:8652196)
    at e.resolveResponse (2.7ac53409.chunk.js:2:8651089)
    at t.<anonymous> (2.7ac53409.chunk.js:2:8655703)
    at 2.7ac53409.chunk.js:2:8654357
    at Object.next (2.7ac53409.chunk.js:2:8654462)
    at s (2.7ac53409.chunk.js:2:8653175)
(anonymous) @ MasterKeyTransfer.tsx:39
```

![image](https://user-images.githubusercontent.com/748181/153728660-33e889dc-abaa-4650-a88c-d83297538167.png)

**Comment by nerveharp** [comment]
Fixed by urbit/bridge#963
