### ISSUE TITLE
Error Report: Cannot read properties of undefined (reading 'value')

### ISSUE THREAD

**Issue by NirTeg** [urbit/bridge#991]
## Error

```
TypeError: Cannot read properties of undefined (reading 'value')
    at https://bridge.urbit.org/static/js/main.e71b7f65.chunk.js:1:223785
    at rs (https://bridge.urbit.org/static/js/2.f7162d00.chunk.js:2:3293092)
    at qs (https://bridge.urbit.org/static/js/2.f7162d00.chunk.js:2:3302659)
    at Qo (https://bridge.urbit.org/static/js/2.f7162d00.chunk.js:2:3346541)
    at xl (https://bridge.urbit.org/static/js/2.f7162d00.chunk.js:2:3332724)
    at Sl (https://bridge.urbit.org/static/js/2.f7162d00.chunk.js:2:3332652)
    at Il (https://bridge.urbit.org/static/js/2.f7162d00.chunk.js:2:3332515)
    at hl (https://bridge.urbit.org/static/js/2.f7162d00.chunk.js:2:3329481)
    at https://bridge.urbit.org/static/js/2.f7162d00.chunk.js:2:3278860
    at t.unstable_runWithPriority (https://bridge.urbit.org/static/js/2.f7162d00.chunk.js:2:3356279)
```

In Bridge version 3.0.0.

**Comment by lukestiles** [comment]
@NirTeg can you share any additional information about what you were doing when this happened?
